// Generated by CoffeeScript 2.2.2
var PresentboxBasic;

PresentboxBasic = (function() {
  class PresentboxBasic extends PresentboxBase {};

  // キャラ名
  PresentboxBasic.characterName = "プレゼント（白）";

  // 画像のリスト
  PresentboxBasic.images = ["./img/presentbox/presentbox_basic.png"];

  PresentboxBasic.abilityName = "アイテムを出す";

  PresentboxBasic.abilityDesc = "倒すとアイテムを入手できる";

  return PresentboxBasic;

}).call(this);
