// Generated by CoffeeScript 2.2.2
var PresentboxN, PresentboxR, PresentboxSR, PresentboxSRp, PresentboxSSR, PresentboxSSRp;

PresentboxN = (function() {
  class PresentboxN extends PresentboxBase {
    getHpMax(level = null) {
      return 3;
    }

  };

  // ID
  PresentboxN.id = 1;

  // キャラ名
  PresentboxN.characterName = "プレゼント（N）";

  // 画像のリスト
  PresentboxN.images = ["./img/presentbox/presentbox_n.png"];

  PresentboxN.receiveTurn = 15;

  PresentboxN.abilityName = PresentboxN.characterName;

  PresentboxN.abilityDesc = '倒すとノーマルなアイテムを入手できる。受取期限は出現してから' + PresentboxN.receiveTurn + 'ターン';

  // アイテムのドロップテーブルID
  PresentboxN.itemTableId = 1;

  // アイテムがジュエルになる時の額
  PresentboxN.itemJewelAmount = 50;

  return PresentboxN;

}).call(this);

PresentboxR = (function() {
  class PresentboxR extends PresentboxBase {
    getHpMax(level = null) {
      return 5;
    }

  };

  // ID
  PresentboxR.id = 2;

  // キャラ名
  PresentboxR.characterName = "プレゼント（R）";

  // 画像のリスト
  PresentboxR.images = ["./img/presentbox/presentbox_r.png"];

  PresentboxR.receiveTurn = 10;

  PresentboxR.abilityName = 'プレゼント★★';

  PresentboxR.abilityDesc = '倒すとレアなアイテムを入手できる。受取期限は出現してから' + PresentboxR.receiveTurn + 'ターン';

  // アイテムのドロップテーブルID
  PresentboxR.itemTableId = 2;

  // アイテムがジュエルになる時の額
  PresentboxR.itemJewelAmount = 100;

  return PresentboxR;

}).call(this);

PresentboxSR = (function() {
  class PresentboxSR extends PresentboxBase {
    getHpMax(level = null) {
      return 8;
    }

  };

  // ID
  PresentboxSR.id = 3;

  // キャラ名
  PresentboxSR.characterName = "プレゼント（SR）";

  // 画像のリスト
  PresentboxSR.images = ["./img/presentbox/presentbox_sr.png"];

  PresentboxSR.receiveTurn = 8;

  PresentboxSR.abilityName = 'プレゼント★★★';

  PresentboxSR.abilityDesc = '倒すとスーパーレアなアイテムを入手できる。受取期限は出現してから' + PresentboxSR.receiveTurn + 'ターン';

  // アイテムのドロップテーブルID
  PresentboxSR.itemTableId = 3;

  // アイテムがジュエルになる時の額
  PresentboxSR.itemJewelAmount = 150;

  return PresentboxSR;

}).call(this);

PresentboxSRp = (function() {
  class PresentboxSRp extends PresentboxBase {
    getHpMax(level = null) {
      return 8;
    }

  };

  // ID
  PresentboxSRp.id = 4;

  // キャラ名
  PresentboxSRp.characterName = "プレゼント（SR+）";

  // 画像のリスト
  PresentboxSRp.images = ["./img/presentbox/presentbox_srp.png"];

  PresentboxSRp.receiveTurn = 6;

  PresentboxSRp.abilityName = 'プレゼント★★★★';

  PresentboxSRp.abilityDesc = '倒すとスーパーレアプラスなアイテムを入手できる。受取期限は出現してから' + PresentboxSRp.receiveTurn + 'ターン';

  // アイテムのドロップテーブルID
  PresentboxSRp.itemTableId = 4;

  // アイテムがジュエルになる時の額
  PresentboxSRp.itemJewelAmount = 200;

  return PresentboxSRp;

}).call(this);

PresentboxSSR = (function() {
  class PresentboxSSR extends PresentboxBase {
    getHpMax(level = null) {
      return 10;
    }

  };

  // ID
  PresentboxSSR.id = 5;

  // キャラ名
  PresentboxSSR.characterName = "プレゼント（SSR）";

  // 画像のリスト
  PresentboxSSR.images = ["./img/presentbox/presentbox_srp.png"];

  PresentboxSSR.receiveTurn = 5;

  PresentboxSSR.abilityName = 'プレゼント★★★★★';

  PresentboxSSR.abilityDesc = '倒すとスーパースーパーレアなアイテムを入手できる。受取期限は出現してから' + PresentboxSSR.receiveTurn + 'ターン';

  // アイテムのドロップテーブルID
  PresentboxSSR.itemTableId = 5;

  // アイテムがジュエルになる時の額
  PresentboxSSR.itemJewelAmount = 250;

  return PresentboxSSR;

}).call(this);

PresentboxSSRp = (function() {
  class PresentboxSSRp extends PresentboxBase {
    getHpMax(level = null) {
      return 12;
    }

  };

  // ID
  PresentboxSSRp.id = 6;

  // キャラ名
  PresentboxSSRp.characterName = "プレゼント（SSR+）";

  // 画像のリスト
  PresentboxSSRp.images = ["./img/presentbox/presentbox_ssrp.png"];

  PresentboxSSRp.receiveTurn = 3;

  PresentboxSSRp.abilityName = 'プレゼント★★★★★';

  PresentboxSSRp.abilityDesc = '倒すとスーパースーパーレアプラスなアイテムを入手できる。受取期限は出現してから' + PresentboxSSRp.receiveTurn + 'ターン';

  // アイテムのドロップテーブルID
  PresentboxSSRp.itemTableId = 6;

  // アイテムがジュエルになる時の額
  PresentboxSSRp.itemJewelAmount = 300;

  return PresentboxSSRp;

}).call(this);
