// Generated by CoffeeScript 2.2.3
var CostManager;

CostManager = (function() {
  class CostManager {
    static init(parentElement) {
      this.parentElement = parentElement;
      this.divObject = $('<div>').attr('id', this.ID).appendTo(this.parentElement);
      this.now = $('<span>').addClass('cost_now').appendTo(this.divObject);
      this.max = $('<span>').addClass('cost_max').appendTo(this.divObject);
      return this.updateCostNow();
    }

    static draw() {
      this.setMax(this.getCostMax());
      return this.setNow(this.getCostNow());
    }

    static setNow(v) {
      return this.now.html(v);
    }

    static setMax(v) {
      return this.max.html(v);
    }

    static getCostMax() {
      return this.DEFAULT + EnvManager.getFloor() * 2;
    }

    static getCostNow() {
      return this.costNow;
    }

    static updateCostNow() {
      this.costNow = FieldManager.getFieldCostContainTemp();
      return this.draw();
    }

  };

  CostManager.ID = 'cost_manager';

  // 最初からあるコスト
  CostManager.DEFAULT = 8;

  return CostManager;

}).call(this);
