// Generated by CoffeeScript 2.2.2
var EnvManager;

EnvManager = (function() {
  class EnvManager {
    static init(parentElement) {
      this.parentElement = parentElement;
      this.lifeObject = $('<div>').attr('id', 'life').appendTo(this.parentElement);
      this.floorObject = $('<div>').attr('id', 'floor').appendTo(this.parentElement);
      this.expObject = $('<div>').attr('id', 'exp').appendTo(this.parentElement);
      this.juwelObject = $('<div>').attr('id', 'juwel').appendTo(this.parentElement);
      return this.draw();
    }

    static draw() {
      this.lifeObject.html('&#9829;' + this.life);
      this.expObject.html(this.exp);
      $('<span>').html('EXP').css({
        left: 0,
        height: 60,
        position: 'absolute'
      }).appendTo(this.expObject);
      this.floorObject.html('公演' + this.floor + '日目');
      this.juwelObject.html(this.juwel);
      return $('<img>').attr('src', './img/juwel.png').css({
        left: 0,
        height: 60,
        position: 'absolute'
      }).appendTo(this.juwelObject);
    }

    static increaseExp(amount) {
      if (amount < 1) {
        return false;
      }
      this.exp += amount;
      this.draw();
      return this.exp;
    }

    static decreaseExp(amount) {
      if (amount < 1) {
        return false;
      }
      if (this.exp < amount) {
        return false;
      }
      this.exp -= amount;
      this.draw();
      return this.exp;
    }

    static getExp() {
      return this.exp;
    }

    static setExp(exp) {
      if (exp < 0) {
        return false;
      }
      this.exp = exp;
      this.draw();
      return this.exp;
    }

    static increaseFloor(amount = 1) {
      if (amount < 1) {
        return false;
      }
      this.floor += amount;
      this.draw();
      return this.floor;
    }

    static decreaseFloor(amount) {
      if (amount < 1) {
        return false;
      }
      if (this.floor - amount < 1) {
        return false;
      }
      this.floor -= amount;
      if (this.floor < 1) {
        this.floor = 1;
      }
      this.draw();
      return this.floor;
    }

    static getFloor() {
      return this.floor;
    }

    static setFloor(floor) {
      if (floor < 1) {
        return false;
      }
      this.floor = floor;
      this.draw();
      return this.floor;
    }

    static increaseLife(amount = 1) {
      if (amount < 1) {
        return false;
      }
      this.life += amount;
      this.draw();
      return this.life;
    }

    static decreaseLife(amount = 1) {
      if (amount < 1) {
        return false;
      }
      if (this.life < amount) {
        return false;
      }
      this.life -= amount;
      if (this.life < 0) {
        this.life = 0;
      }
      this.draw();
      return this.life;
    }

    static getLife() {
      return this.life;
    }

    static setLife(life) {
      if (life < 0) {
        return false;
      }
      this.life = life;
      this.draw();
      return this.life;
    }

    static increaseJuwel(amount) {
      if (amount < 1) {
        return false;
      }
      this.juwel += amount;
      this.draw();
      return this.juwel;
    }

    static decreaseJuwel(amount) {
      if (amount < 1) {
        return false;
      }
      if (this.juwel < amount) {
        return false;
      }
      this.juwel -= amount;
      if (this.juwel < 0) {
        this.juwel = 0;
      }
      this.draw();
      return this.juwel;
    }

    static getJuwel() {
      return this.juwel;
    }

    static setJuwel(juwel) {
      if (juwel < 0) {
        return false;
      }
      this.juwel = juwel;
      this.draw();
      return this.juwel;
    }

  };

  EnvManager.ID = 'env';

  EnvManager.exp = 0;

  EnvManager.floor = 1;

  EnvManager.life = 5;

  EnvManager.juwel = 0;

  return EnvManager;

}).call(this);
