// Generated by CoffeeScript 2.2.2
var InfoManager;

InfoManager = class InfoManager {
  static init(parentElement) {
    this.parentElement = parentElement;
    this.divObject = $('<div>').attr('id', this.ID).css({
      width: Panel.SIZE_X,
      height: Panel.SIZE_Y,
      "background-color": '#000000'
    }).appendTo(this.parentElement);
    return this.panel = new Panel(this.divObject, null, null, null, false, false, true);
  }

  static setObject(object = null) {
    this.panel.object = object;
    return this.panel.draw();
  }

  static show() {
    return this.divObject.addClass('no_display');
  }

  static hide() {
    return this.divObject.addClass('no_display');
  }

};
