// Generated by CoffeeScript 2.2.2
var LeftInfoManager;

LeftInfoManager = (function() {
  class LeftInfoManager extends InfoManager {};

  LeftInfoManager.ID = 'left_info';

  return LeftInfoManager;

}).call(this);
