// Generated by CoffeeScript 2.2.2
var LevelupManager;

LevelupManager = (function() {
  class LevelupManager {
    static init(parentElement) {
      var cObj, k, ref, results;
      this.parentElement = parentElement;
      this.divObject = $('<div>').attr('id', this.ID).css({
        width: this.SIZE_X,
        height: this.SIZE_Y
      }).appendTo(this.parentElement);
      this.characters = [];
      ref = GameManager.characters;
      results = [];
      for (k in ref) {
        cObj = ref[k];
        results.push(this.characters.push(cObj));
      }
      return results;
    }

    static draw() {
      var c, i, index, len, ref, results, top;
      this.characters.sort(function(a, b) {
        return Number(a.getId()) - Number(b.getId());
      });
      this.panels = [];
      $('#' + this.ID + ' > .' + LevelupPanel.CLASSNAME).remove();
      ref = this.characters;
      results = [];
      for (index = i = 0, len = ref.length; i < len; index = ++i) {
        c = ref[index];
        top = index * LevelupPanel.SIZE_Y;
        results.push(this.panels.push(new LevelupPanel(this.divObject, c, top)));
      }
      return results;
    }

    static show() {
      return this.divObject.addClass('no_display');
    }

    static hide() {
      return this.divObject.addClass('no_display');
    }

  };

  LevelupManager.ID = 'levelup';

  LevelupManager.SIZE_X = 1050;

  LevelupManager.SIZE_Y = 600;

  return LevelupManager;

}).call(this);
