// Generated by CoffeeScript 2.2.2
var ObjectBase;

ObjectBase = (function() {
  class ObjectBase {
    constructor(objectType) {
      this.objectType = objectType;
    }

    getObjectType() {
      return this.objectType;
    }

    isCharacterObject() {
      return this.objectType === this.constructor.OBJECT_TYPE.CHARACTER;
    }

    isEnemyObject() {
      return this.objectType === this.constructor.OBJECT_TYPE.ENEMY;
    }

    isPresentObject() {
      return this.objectType === this.constructor.OBJECT_TYPE.PRESENTBOX;
    }

    getHpMax(level = null) {
      if (level === null) {
        return this.constructor.hpBase * this.level;
      } else {
        return this.constructor.hpBase * level;
      }
    }

    getHp() {
      if (this.hp === null || this.getHpMax() < this.hp) {
        return this.getHpMax();
      } else if (this.hp <= 0) {
        return 0;
      } else {
        return this.hp;
      }
    }

    damage(amount) {
      if (amount <= 0) {
        return false;
      }
      this.hp = this.getHp() - amount;
      return this.getHp();
    }

    getLevel(level = null) {
      if (level === null) {
        return this.level;
      } else {
        return level;
      }
    }

    setLevel(level) {
      return this.level = level;
    }

    levelup(level) {
      return this.level += level;
    }

    getCharacterName() {
      return this.constructor.characterName;
    }

    getAttackType() {
      return this.constructor.attackTypeBase;
    }

    getAttack(level = null) {
      if (level === null) {
        return Math.ceil(this.constructor.attackBase * this.level);
      } else {
        return Math.ceil(this.constructor.attackBase * level);
      }
    }

    getAttackBase() {
      return this.constructor.attackBase;
    }

    getPDef(level = null) {
      if (level === null) {
        return Math.ceil(this.constructor.pDefBase * this.level);
      } else {
        return Math.ceil(this.constructor.pDefBase * level);
      }
    }

    getPDefBase() {
      return this.constructor.pDefBase;
    }

    getMDef(level = null) {
      if (level === null) {
        return Math.ceil(this.constructor.mDefBase * this.level);
      } else {
        return Math.ceil(this.constructor.mDefBase * level);
      }
    }

    getMDefBase() {
      return this.constructor.mDefBase;
    }

    getMove() {
      return this.constructor.moveBase;
    }

    getMoveBase() {
      return this.constructor.moveBase;
    }

    getRange() {
      return this.constructor.rangeBase;
    }

    getRangeBase() {
      return this.constructor.rangeBase;
    }

    getHitRate() {
      return this.constructor.hitRateBase;
    }

    getHitRateBase() {
      return this.constructor.hitRateBase;
    }

    getDodgeRate() {
      return this.constructor.dodgeRateBase;
    }

    getDodgeRateBase() {
      return this.constructor.dodgeRateBase;
    }

    getExp() {
      return Math.ceil(this.level * this.constructor.expRate);
    }

    getAbilityName() {
      return this.constructor.abilityName;
    }

    getAbilityDesc() {
      return this.constructor.abilityDesc;
    }

    getBaseImage() {
      return this.constructor.images[0];
    }

    getImages() {
      return this.constructor.images;
    }

    getImage(index) {
      if (!((0 <= index && index < this.constructor.images.length))) {
        return null;
      }
      return this.constructor.images[index];
    }

    // 指定したレベル上がるために必要な経験値量
    getNeededExp(level) {
      var baseExp, baseLevel, targetExp, targetLevel;
      targetLevel = this.level + level;
      baseLevel = this.level;
      targetExp = (Math.pow(targetLevel, 2)) * this.constructor.expRate;
      baseExp = (Math.pow(baseLevel, 2)) * this.constructor.expRate;
      return Math.ceil(targetExp - baseExp);
    }

    // 経験値で上げられるレベル量
    getLevelUpMax(exp) {
      var baseExp, targetExp;
      baseExp = (Math.pow(this.level, 2)) * this.constructor.expRate;
      targetExp = baseExp + exp;
      return Math.floor(Math.sqrt(targetExp / this.constructor.expRate) - this.level);
    }

    // ダメージ計算式
    static getDamageMin(attack, def) {
      var damage;
      damage = attack - def;
      if (damage < 1) {
        return 1;
      }
      damage = Math.round(damage - damage * this.DAMAGE_SHAKE_RATE);
      if (damage < 1) {
        return 1;
      }
      return damage;
    }

    static getDamageMax(attack, def) {
      var damage;
      damage = attack - def;
      if (damage < 1) {
        return 1;
      }
      damage = Math.round(damage + damage * this.DAMAGE_SHAKE_RATE);
      if (damage < 1) {
        return 1;
      }
      return damage;
    }

    static getDamage(attack, def) {
      return Utl.rand(this.getDamageMin(attack, def), this.getDamageMax(attack, def));
    }

    static getKnockoutRate(hp, attack, def) {
      var max, min;
      min = this.getDamageMin(attack, def);
      max = this.getDamageMax(attack, def);
      if (hp <= min) {
        return +2e308;
      } else if (hp <= max) {
        return Math.round((max - hp + 1) / (max - min + 1) * 100);
      } else {
        return -2e308;
      }
    }

  };

  ObjectBase.OBJECT_TYPE = {
    CHARACTER: 'CHARACTER',
    ENEMY: 'ENEMY',
    PRESENTBOX: 'PRESENTBOX'
  };

  ObjectBase.ATTACK_TYPE = {
    PHYSIC: '物理',
    MAGIC: '魔法'
  };

  // ダメージの振れ幅
  ObjectBase.DAMAGE_SHAKE_RATE = 0.1;

  // 倒せるか定数兼画像
  ObjectBase.KNOCKOUT = {
    OK: './img/circle.png',
    MAY: './img/triangle.png',
    NG: './img/cross.png'
  };

  return ObjectBase;

}).call(this);
