// Generated by CoffeeScript 2.2.2
var Panel;

Panel = (function() {
  class Panel {
    constructor(parentElement, object, posY = 0, posX = 0, isShowOverlay = true, isCharacterPallet = false) {
      this.parentElement = parentElement;
      this.object = object;
      this.posY = posY;
      this.posX = posX;
      this.isShowOverlay = isShowOverlay;
      this.isCharacterPallet = isCharacterPallet;
      this.divObject = $('<div>').addClass(this.constructor.CLASSNAME).css({
        width: this.constructor.SIZE_X,
        height: this.constructor.SIZE_Y,
        top: this.posY,
        left: this.posX
      }).appendTo(this.parentElement);
      this.draw();
    }

    // アイコンがドラッグ開始された時
    onIconDragStart(evt) {
      if (!GameManager.isControllable()) {
        return;
      }
      // キャラクター出撃に使っていいパネルではないなら帰る
      if (!this.isCharacterPallet) {
        return;
      }
      // キャラクター出撃モードではないので帰る
      if (!GameManager.isMode.characterPick) {
        return;
      }
      // キャラクターではないので帰る
      if (!this.object.isCharacterObject()) {
        return;
      }
      if (this.object.isInField()) {
        // 既に出撃中なので帰る
        return true;
      }
      CharacterPalletManager.pickCharacter(this.object);
      return true;
    }

    draw(level = null) {
      $(this.divObject).find('*').remove();
      if (this.object !== null) {
        this.drawCommon(level);
        if (this.object.isCharacterObject()) {
          return this.drawCharacter(level);
        } else if (this.object.isEnemyObject()) {
          return this.drawEnemy();
        } else if (this.object.isPresentboxObject()) {
          return this.drawEnemy();
        }
      } else {
        return this.clear();
      }
    }

    drawCommon(level = null) {
      // アイコン
      $(this.divObject).append($('<div>').addClass('field field_icon').css({
        top: 32,
        left: 5,
        width: 80,
        height: 80,
        "background-image": 'url(' + this.object.getBaseImage() + ')'
      }).on('mousedown', (evt) => {
        if (evt.which === 1) {
          this.onIconDragStart.bind(this)(evt);
        }
        return true;
      }));
      // レベル
      $(this.divObject).append($('<div>').addClass('field field_level').css({
        top: 95,
        left: 5,
        width: 75,
        height: 20
      }).html('Lv.' + ObjectBase.status2html(this.object.getLevel(level))));
      // 名前
      $(this.divObject).append($('<div>').addClass('field field_name').css({
        top: 5,
        left: 10,
        width: 190,
        height: 20,
        color: '#ffffff',
        'font-weight': 'bold',
        'text-align': 'left',
        'line-height': '20px'
      }).html(this.object.getCharacterName()));
      // 攻撃力
      $(this.divObject).append($('<div>').addClass('field field_attack ' + (this.object.getAttackType() === '物理' ? 'field_attack_physic' : 'field_attack_magic')).css({
        top: 30,
        left: 130,
        width: 90,
        height: 20
      }).html(ObjectBase.status2html(this.object.getAttack(level))));
      // 物理防御力
      $(this.divObject).append($('<div>').addClass('field field_pdef').css({
        top: 51,
        left: 130,
        width: 90,
        height: 20
      }).html(ObjectBase.status2html(this.object.getPDef(level))));
      // 魔法防御力
      $(this.divObject).append($('<div>').addClass('field field_mdef').css({
        top: 71,
        left: 130,
        width: 90,
        height: 20
      }).html(ObjectBase.status2html(this.object.getMDef(level))));
      // HP
      $(this.divObject).append($('<div>').addClass('field field_hp').css({
        top: 7,
        left: 220,
        width: 80,
        height: 20
      }).html(ObjectBase.status2html(this.object.getHp())));
      // HP最大
      $(this.divObject).append($('<div>').addClass('field field_hp_max').css({
        top: 7,
        left: 305,
        width: 80,
        height: 20
      }).html(ObjectBase.status2html(this.object.getHpMax(level))));
      // 命中率
      $(this.divObject).append($('<div>').addClass('field field_hit_rate').css({
        top: 30,
        left: 280,
        width: 25,
        height: 20
      }).html(ObjectBase.status2html(this.object.getHitRate())));
      // 回避率
      $(this.divObject).append($('<div>').addClass('field field_dodge_rate').css({
        top: 51,
        left: 280,
        width: 25,
        height: 20
      }).html(ObjectBase.status2html(this.object.getDodgeRate())));
      // 移動力
      $(this.divObject).append($('<div>').addClass('field field_move').css({
        top: 30,
        left: 360,
        width: 20,
        height: 20
      }).html(ObjectBase.status2html(this.object.getMove())));
      // 射程
      $(this.divObject).append($('<div>').addClass('field field_range').css({
        top: 50,
        left: 360,
        width: 20,
        height: 20
      }).html(this.object.getRange()));
      // 能力
      return $(this.divObject).append($('<div>').addClass('field field_ability').css({
        top: 93,
        left: 130,
        width: 100,
        height: 20,
        'text-align': 'left'
      }).html(this.object.getAbilityName()).tooltip({
        'placement': 'top',
        'title': this.object.getAbilityDesc()
      }));
    }

    drawCharacter(level = null) {
      // 背景用
      this.divObject.addClass('panel_character');
      if (this.isShowOverlay) {
        // 出撃中判定
        if (this.object.isInField()) {
          return $('<div>').addClass('infield').appendTo(this.divObject);
        // 療養中判定
        } else if (this.object.getComebackTurn() > 0) {
          return $('<div>').addClass('comeback').html(this.object.getComebackTurn()).appendTo(this.divObject);
        }
      }
    }

    drawEnemy() {
      // 背景用
      return this.divObject.addClass('panel_enemy');
    }

    drawPresentbox() {}

    clear() {
      return $(this.divObject).find('*').remove();
    }

    removeMe() {
      $(this.divObject).find('*').remove();
      return $(this.divObject).remove();
    }

  };

  Panel.SIZE_X = 400;

  Panel.SIZE_Y = 120;

  Panel.CLASSNAME = 'panel';

  return Panel;

}).call(this);
