// Generated by CoffeeScript 2.2.3
var RightInfoManager;

RightInfoManager = (function() {
  class RightInfoManager extends InfoManager {};

  RightInfoManager.ID = 'right_info';

  return RightInfoManager;

}).call(this);
