// Generated by CoffeeScript 2.2.2
var SaveManager;

SaveManager = class SaveManager {
  static generateSavedata() {
    var c, characters, env, i, item, items, j, len, len1, ref, ref1;
    // キャラクター
    characters = [];
    ref = GameManager.characters;
    for (i = 0, len = ref.length; i < len; i++) {
      c = ref[i];
      characters.push(c.serialize());
    }
    // アイテム
    items = [];
    ref1 = ItemManager.items;
    for (j = 0, len1 = ref1.length; j < len1; j++) {
      item = ref1[j];
      items.push(item);
    }
    // 環境
    return env = {
      exp: EnvManager.getExp(),
      floor: EnvManager.getFloor(),
      life: EnvManager.getLife(),
      juwel: EnvManager.getJuwel()
    };
  }

};

// フィールド
