// Generated by CoffeeScript 2.2.2
window.UnitList = [
  {
    "name": "\u30a2\u30fc\u30c6\u30a3\u30b9\u30bf\u30fc",
    "id": [193,
  74],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u3042\u30fc\u306b\u3083\u3093\u307f\u304f\u306b\u3083\u3093",
    "id": [12,
  154],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30a4\u30ab\u30d0\u30e9\u30d7\u30ea\u30f3\u30bb\u30b9",
    "id": [83,
  23],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30a4\u30f3\u30c7\u30a3\u30b4\u30fb\u30d9\u30eb",
    "id": [108,
  114],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u7b11\u7f8e\u3068\u9234\u5e06\u306e\u7206\u7b11\u30a8\u30d6\u30ea\u30c7\u30a4",
    "id": [122,
  26],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30a8\u30bf\u30fc\u30ca\u30eb\u30ec\u30c7\u30a3\u30a8\u30a4\u30c8",
    "id": [86,
  87],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u8d8a\u5f8c\u5c0f\u753a",
    "id": [29,
  43],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30a8\u30eb\u30c9\u30ea\u30c3\u30c1\u30fb\u30ed\u30a2\u30c6\u30e9\u30fc",
    "id": [96,
  157],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30a8\u30ec\u30ac\u30f3\u30c8\u30a4\u30f3\u30e2\u30e9\u30ea\u30b9\u30c8",
    "id": [199,
  113],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u304b\u306a\u2606\u304b\u306a\u2606\u3075\u3041\u3093\u3057\u30fc",
    "id": [24,
  171],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u58c1\u30b5\u30fc\u306e\u82b1",
    "id": [36,
  15],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ab\u30ef\u30b9\u30a6\u30a3\u30fc\u30c6\u30a3\u30fc\u306a\u30dc\u30af\u306f\u3041\u3068(\u4eee)",
    "id": [64,
  86],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30af\u30e9\u30d9\u30fc\u30eb\u30c4\u30a4\u30f3",
    "id": [99,
  130],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u6708\u4e0b\u6c37\u59eb",
    "id": [144,
  81],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b5\u30fc\u30c1&\u30b8\u30e3\u30c3\u30b8\u30e1\u30f3\u30c8",
    "id": [17,
  79],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b5\u30a4\u30ad\u30c3\u30af\u30d2\u30fc\u30c4",
    "id": [138,
  153],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b5\u30a4\u30d0\u30fc\u30b0\u30e9\u30b9",
    "id": [44,
  15],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b5\u30a4\u30ec\u30f3\u30c8\u30b9\u30af\u30ea\u30fc\u30de\u30fc",
    "id": [182,
  152],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b5\u30af\u30e9\u30d6\u30ed\u30c3\u30b5\u30e0",
    "id": [35,
  4],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u3055\u3064\u304d\u306e\u9803",
    "id": [132,
  43],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u5c71\u7d2b\u6c34\u660e",
    "id": [144,
  194],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b7\u30e3\u30a4\u30cb\u30fc\u30fb\u30a2\u30fc\u30ea\u30fc\u30c7\u30a4\u30ba",
    "id": [170,
  13],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u8972\u6483!\u30c7\u30d3\u30eb\u30a2\u30c4\u30df",
    "id": [175,
  187],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u3057\u3085\u304c\u3057\u3085\u304c\u2606\u307f\uff5e\u3093",
    "id": [86,
  13],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b7\u30f3\u30d5\u30a9\u30cb\u30c3\u30af\u30fb\u30ef\u30fc\u30eb\u30c9",
    "id": [16,
  28],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b9\u30a6\u30a3\u30fc\u30c8\u30e9\u30f4\u30a1\u30fc\u30ba",
    "id": [115,
  171],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b9\u30bf\u30fc\u30b9\u30af\u30ec\u30a4\u30d1\u30fc",
    "id": [186,
  184],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b9\u30ce\u30fc\u30d5\u30a3\u30fc\u30e6",
    "id": [85,
  188],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b9\u30c8\u30ec\u30fc\u30c8\u30d5\u30eb\u30fc\u30c8",
    "id": [117,
  168],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b9\u30d1\u30cb\u30c3\u30b7\u30e5\u30b9\u30bf\u30a4\u30eb",
    "id": [153,
  27],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u3059\u307e\u3044\u308b\u306f\u3063\u3074\u30fc\u3082\u3093\u3059\u305f\u30fc",
    "id": [16,
  128],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30bb\u30fc\u30e9\u30fc\u30de\u30ea\u30ca\u30fc",
    "id": [165,
  159],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30bb\u30d7\u30c6\u30f3\u30d0\u30fc\u30ea\u30fc\u30d6\u30b9",
    "id": [60,
  57],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30bb\u30f3\u30b4\u30af\u2606\u30e9\u30f3\u30d6",
    "id": [127,
  132],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30bd\u30eb\u30fb\u30ab\u30de\u30eb",
    "id": [118,
  195],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30c0\u30fc\u30af\u30a4\u30eb\u30df\u30cd\u30a4\u30c8",
    "id": [126,
  47],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30c1\u30fc\u30e0\u30fb\u30d5\u30e9\u30ef\u30fc",
    "id": [88,
  38],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30c7\u30a2\u30fb\u30a2\u30a6\u30ed\u30fc\u30e9",
    "id": [134,
  125],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30c7\u30a3\u30c6\u30af\u30c6\u30a3\u30d6\u30f4\u30a1\u30fc\u30b5\u30b9",
    "id": [17,
  148],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30c6\u30f3\u30d7\u30c6\u30fc\u30b7\u30e7\u30f3\u30fb\u30a2\u30a4\u30ba",
    "id": [89,
  172],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ca\u30a4\u30c8\u30d6\u30eb\u30fc\u30ec\u30b6\u30fc",
    "id": [21,
  62],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u5fcd\u6b66\u2606\u7e5a\u4e71",
    "id": [132,
  198],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ce\u30fc\u30c6\u30a3\u30ae\u30e3\u30eb\u30ba",
    "id": [174,
  143],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30cf\u30fc\u30c8\u30cf\u30fc\u30e2\u30ca\u30a4\u30ba",
    "id": [19,
  193],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u7fbd\u8863\u5c0f\u753a",
    "id": [66,
  89],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u306f\u3074\u2606\u304b\u3080",
    "id": [24,
  186],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d0\u30ea\u30b9\u30bf\u30a4\u30eb",
    "id": [55,
  155],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u6625\u8272\u59eb\u541b",
    "id": [66,
  73],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30cf\u30ef\u30a4\u30a2\u30f3\u30c4\u30a4\u30f3",
    "id": [175,
  186],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d3\u30fc\u30c8\u30b7\u30e5\u30fc\u30bf\u30fc",
    "id": [190,
  161],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d2\u30fc\u30ed\u30fc\u30f4\u30a1\u30fc\u30b5\u30b9",
    "id": [65,
  121],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u3072\u3064\u3058\u3055\u3093\u3068\u3046\u3055\u304e\u3055\u3093",
    "id": [63,
  190],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u65e5\u83dc\u5b50\u3068\u611b\u6d77\u306e\u5984\u60f3\u30ef\u30fc\u30eb\u30c9",
    "id": [175,
  50],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d4\u30e5\u30a2\u30ea\u30fc\u30c4\u30a4\u30f3",
    "id": [10,
  41],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d2\u30ed\u30a4\u30c3\u30af\u30a8\u30f3\u30b8\u30a7\u30eb",
    "id": [121,
  64],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d5\u30a1\u30df\u30ea\u30a2\u30c4\u30a4\u30f3",
    "id": [93,
  94],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d5\u30a3\u30aa\u30ec\u30f3\u30c6\u30a3\u30ca",
    "id": [6,
  76],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d5\u30a3\u30eb\u30e0\u30fb\u30e1\u30e2\u30ea\u30a2\u30eb",
    "id": [108,
  29],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d5\u30a9\u30fc\u30ea\u30f3\u30b7\u30fc\u30b5\u30a4\u30c9",
    "id": [46,
  176],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d6\u30ea\u30e4\u30f3\u30c8\u30ce\u30ef\u30fc\u30eb",
    "id": [61,
  167],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d9\u30bf\u30fc\u30fb\u30b0\u30ed\u30a6",
    "id": [105,
  136],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30dc\u30fc\u30eb\u30fb\u30d5\u30ec\u30f3\u30ba\uff0f\u30ea\u30fc\u30d7\u30fb\u30b9\u30b3\u30a2\u30e9\u30fc",
    "id": [139,
  190],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30df\u30b9\u30c6\u30ea\u30a2\u30b9\u30a2\u30a4\u30ba",
    "id": [134,
  103],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30df\u30b9\u30c6\u30ea\u30a2\u30b9\u30ac\u30fc\u30eb\u30ba",
    "id": [142,
  153],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30df\u30b9\u30c6\u30ea\u30c3\u30af\u30ac\u30fc\u30c7\u30f3",
    "id": [126,
  6],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30df\u30b9\u30fb\u30d5\u30a9\u30fc\u30c1\u30e5\u30f3",
    "id": [95,
  106],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30e0\u30b7\u30d0\u30ec\u30a4\u30ca\u3068\u5c0f\u6625\u3061\u3083\u3093",
    "id": [63,
  65],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30e2\u30ce\u30af\u30ed\u30fc\u30e0\u30ea\u30ea\u30a3",
    "id": [134,
  150],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u3082\u3082\u3079\u308a\u30fc",
    "id": [83,
  110],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u3088\u3046\u305b\u3044\u3055\u3093\u3068\u304a\u306d\u3048\u3055\u3093",
    "id": [55,
  191],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30e9\u30d6\u30ea\u30fc\u30c0\u30a4\u30ca\u30fc\u30ba",
    "id": [103,
  119],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ea\u30c8\u30eb\u30d2\u30fc\u30ed\u30fc",
    "id": [121,
  192],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ec\u30a4\u30b8\u30fc\u30fb\u30ec\u30a4\u30b8\u30fc",
    "id": [172,
  22],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ec\u30a4\u30fb\u30c7\u30a3\u30b9\u30bf\u30f3\u30b9",
    "id": [103,
  46],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ec\u30c3\u30c9\u30d9\u30ea\u30a3\u30ba",
    "id": [110,
  176],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ec\u30c7\u30a3\u30d3\u30fc\u30b9\u30c8",
    "id": [105,
  52],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ed\u30dc\u30d5\u30ec\u30f3\u30ba",
    "id": [20,
  195],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Ai's",
    "id": [108,
  115],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\uff0a",
    "id": [154,
  109],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "B.B",
    "id": [32,
  37],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Dimension-3",
    "id": [22,
  126],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "ERICATHY",
    "id": [9,
  54],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "FrenchKisS",
    "id": [172,
  134],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Flowery",
    "id": [108,
  6],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "HappyHappyTwin",
    "id": [145,
  183],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Jumpin'Joker",
    "id": [8,
  96],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "LOVE LAIKA",
    "id": [125,
  12],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "NiGHT ENCOUNTER",
    "id": [152,
  96],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "P\u30fbU",
    "id": [153,
  13],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Red-Solids",
    "id": [77,
  56],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Rock the Beat",
    "id": [109,
  53],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Rosenburg Alptraum",
    "id": [96,
  47],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Shock'in Pink!",
    "id": [143,
  133],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30a2\u30cb\u30de\u30eb\u30d1\u30fc\u30af",
    "id": [57,
  170,
  23],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30a2\u30f3\u30c0\u30fc\u30b6\u30c7\u30b9\u30af",
    "id": [182,
  152,
  82],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30a4\u30bf\u30ea\u30a2\u30f3\u30b9\u30bf\u30a4\u30eb",
    "id": [80,
  149,
  128],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30a6\u30a3\u30f3\u30bf\u30fc\u30fbF\u30fb\u30c9\u30e9\u30a4\u30d0\u30fc\u30ba",
    "id": [135,
  106,
  139],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u685c\u82b1\u5c0f\u753a",
    "id": [181,
  113,
  43],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ac\u30fc\u30eb\u30ba\u30fb\u30d1\u30ef\u30fc",
    "id": [111,
  48,
  30],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ab\u30ef\u30a4\u30a4\u30dc\u30af\u3068142's",
    "id": [64,
  96,
  152],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u4eac\u753a\u4e59\u5973",
    "id": [40,
  45,
  183],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b0\u30e9\u30b9\u30d5\u30eb\u30ef\u30fc\u30eb\u30c9",
    "id": [10,
  44,
  49],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b4\u30b9\u30da\u30eb\u30b7\u30b9\u30bf\u30fc\u30ba",
    "id": [196,
  16,
  142],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b5\u30de\u30fc\u30e9\u30a4\u30d6\u30bb\u30fc\u30e9\u30fc",
    "id": [60,
  125,
  173],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b7\u30e3\u30a4\u30cb\u30f3\u30b0\u30b4\u30c3\u30c9\u30c1\u30a7\u30ea\u30fc",
    "id": [152,
  45,
  40],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b8\u30e3\u30dd\u30cd\u30b9\u30af",
    "id": [106,
  114,
  194],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b9\u30da\u30fc\u30b9\u30b9\u30bf\u30a4\u30eb",
    "id": [191,
  193,
  124],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30c1\u30e3\u30ec\u30f3\u30b8\u30af\u30c3\u30ad\u30f3\u30b0",
    "id": [76,
  110,
  139],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30c9\u30a4\u30c4\u30b9\u30bf\u30a4\u30eb",
    "id": [38,
  21,
  49],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30cb\u30e5\u30fc\u30a4\u30e4\u30fc\u30b9\u30bf\u30a4\u30eb",
    "id": [20,
  195,
  161],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30cb\u30e5\u30fc\u30a6\u30a7\u30fc\u30d6",
    "id": [177,
  33,
  112],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30cb\u30e5\u30fc\u30fb\u30ef\u30fc\u30eb\u30c9\u30fb\u30aa\u30fc\u30c0\u30fc",
    "id": [59,
  118,
  149],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30cf\u30fc\u30c8\u30a6\u30a9\u30fc\u30de\u30fc",
    "id": [25,
  142,
  97],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30cf\u30ed\u30a6\u30a3\u30f3\u30f4\u30a1\u30f3\u30d1\u30a4\u30a2",
    "id": [99,
  52,
  51],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d1\u30ef\u30d5\u30eb\u30d2\u30fc\u30e9\u30fc\u30ba",
    "id": [20,
  92,
  39],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d3\u30d3\u30c3\u30c9\u30ab\u30e9\u30fc\u30a8\u30a4\u30b8\uff0fAge16",
    "id": [24,
  144,
  108],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30db\u30fc\u30ea\u30fc\u30ca\u30a4\u30c8\u30a6\u30a3\u30c3\u30b7\u30e5",
    "id": [18,
  59,
  180],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u3082\u3082\u307a\u3042\u3079\u308a\u30fc",
    "id": [83,
  161,
  110],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ea\u30c8\u30eb\u30b9\u30de\u30a4\u30eb\u30ba",
    "id": [8,
  84,
  192],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ea\u30c8\u30eb\u30c1\u30a7\u30ea\u30fc\u30d6\u30ed\u30c3\u30b5\u30e0",
    "id": [39,
  83,
  196],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ec\u30a4\u30f3\u30c9\u30ed\u30c3\u30d7",
    "id": [135,
  198,
  35],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ed\u30c3\u30ad\u30f3\u30b0\u30ac\u30fc\u30eb",
    "id": [109,
  171,
  94],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "BLACK DESIRE",
    "id": [152,
  61,
  36],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "individuals",
    "id": [182,
  152,
  133],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "new generations",
    "id": [1,
  2,
  3],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30a2\u30c3\u30d7\u30c8\u30a5\u30c7\u30a4\u30c8",
    "id": [165,
  159,
  34],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30a2\u30f3\u30c1\u30a7\u30a4\u30f3\u30fb\u30b7\u30b0\u30ca\u30eb",
    "id": [52,
  152,
  165],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ae\u30e3\u30eb\u30ba\u30d1\u30fc\u30c6\u30a3\u30fc",
    "id": [101,
  143,
  35],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b7\u30ac\u30fc\u30fb\u30b9\u30a6\u30a3\u30fc\u30c8",
    "id": [120,
  142,
  10],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b9\u30a6\u30a3\u30fc\u30c8\u30fb\u30e9\u30d6\u30fb\u30b9\u30a6\u30a3\u30fc\u30c8",
    "id": [80,
  115,
  171],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b9\u30a6\u30a3\u30fc\u30c8\u30c6\u30a3\u30fc\u30bf\u30a4\u30e0",
    "id": [7,
  59,
  155],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30bb\u30af\u30b7\u30fc\u30ae\u30e3\u30eb\u30ba",
    "id": [35,
  93,
  143],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u3068\u304d\u3081\u304d\u30aa\u30fc\u30b7\u30e3\u30f3",
    "id": [11,
  100,
  116],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30c9\u30ea\u30fc\u30e0\u30db\u30fc\u30d7\u30b9\u30d7\u30ea\u30f3\u30b0",
    "id": [120,
  180,
  63],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u9577\u5d0e\u89aa\u5584\u5927\u4f7f",
    "id": [52,
  16,
  39],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u8679\u8272\u30c9\u30ea\u30fc\u30de\u30fc",
    "id": [45,
  15,
  13],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u306b\u3083\u3093\u30fb\u306b\u3083\u3093\u30fb\u306b\u3083\u3093",
    "id": [154,
  107,
  12],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30cf\u30fc\u30c9\u30e1\u30c6\u30aa\u30e9\u30a4\u30c4",
    "id": [52,
  193,
  53],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d3\u30c3\u30b0\u30fb\u30bb\u30d1\u30ec\u30fc\u30c8\u30fb\u30b9\u30ea\u30fc",
    "id": [130,
  92,
  30],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d3\u30e5\u30fc\u30c6\u30a3\u30fc\u30a2\u30ea\u30e5\u30fc\u30eb",
    "id": [75,
  160,
  131],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u3077\u3061\u3063\u3068\u30ca\u30a4\u30f3",
    "id": [196,
  23,
  192],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d5\u30e9\u30f3\u30e1\u30fb\u30eb\u30fc\u30b8\u30e5",
    "id": [55,
  74,
  155],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d6\u30eb\u30fc\u30e0\u30b8\u30e3\u30fc\u30cb\u30fc",
    "id": [27,
  120,
  63],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d8\u30eb\u30b7\u30fc\u30b5\u30d0\u30a4\u30d6",
    "id": [189,
  60,
  98],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30db\u30c3\u30c8\u30a2\u30fc\u30c8\u30b8\u30e3\u30f3\u30d4\u30f3",
    "id": [124,
  5,
  193],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30de\u30c3\u30b7\u30d6\u30e9\u30a4\u30c0\u30fc\u30b9",
    "id": [53,
  174,
  143],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u5bae\u57ce\u89aa\u5584\u5927\u4f7f",
    "id": [14,
  82,
  133],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u5973\u795e\u305f\u3061\u306e\u590f\u5bb4",
    "id": [103,
  43,
  46],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30e6\u30a2\u30fb\u30d5\u30ec\u30f3\u30ba",
    "id": [118,
  62,
  178],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u8a98\u60d1\u30a4\u30d3\u30eb",
    "id": [22,
  172,
  89],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30e9\u30a6\u30c9\u30b7\u30e3\u30a6\u30c8\u30d3\u30fc\u30c4",
    "id": [101,
  157,
  193],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u843d\u82b1\u6d41\u6c34",
    "id": [82,
  96,
  150],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30e9\u30d3\u30e5\u30fc\u2606\u30a2\u30a4\u30b9\u2606\u30de\u30a6\u30f3\u30c6\u30f3",
    "id": [80,
  175,
  122],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ef\u30f3\u30b9\u30c6\u30c3\u30d7\u30b9",
    "id": [99,
  95,
  182],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "GIRLS BE",
    "id": [99,
  95,
  156],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "KBYD",
    "id": [64,
  66,
  139],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "thinE\/Dasein",
    "id": [16,
  126,
  100],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Violet Violence",
    "id": [56,
  77,
  107],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ad\u30d5\u30b8\u30f3\u30ad\u30d6\u30f3",
    "id": [34,
  36,
  57],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b9\u30b1\u30eb\u30c4\u30a9\u30fb\u30d7\u30ea\u30de\u30f4\u30a7\u30fc\u30e9",
    "id": [177,
  38,
  24],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ce\u30fc\u30d6\u30eb\u30bb\u30ec\u30d6\u30ea\u30c6\u30a3",
    "id": [168,
  98,
  76],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d4\u30f3\u30ad\u30fc\u30ad\u30e5\u30fc\u30c8",
    "id": [1,
  73,
  40],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30e1\u30ed\u30a6\u30fb\u30a4\u30a8\u30ed\u30fc",
    "id": [117,
  168,
  88],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u308a\u308b\u3059\u305f\u30fc",
    "id": [17,
  24,
  158],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "CANDY ISLAND",
    "id": [171,
  145,
  40],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "P.C.S",
    "id": [1,
  73,
  19],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "TIP! TAP!",
    "id": [42,
  60,
  158],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "397cherry",
    "id": [154,
  13,
  40],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30a2\u30a4\u30c9\u30eb\u30df\u30ba\u30ad with AS",
    "id": [113,
  46,
  193],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30c8\u30e9\u30f3\u30af\u30a3\u30eb\u30fb\u30a6\u30a3\u30b9\u30d1\u30fc",
    "id": [12,
  81,
  103],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d0\u30ec\u30f3\u30bf\u30a4\u30f3\u53cd\u7701\u4f1a",
    "id": [199,
  130,
  170],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d5\u30a1\u30bf\u30fb\u30e2\u30eb\u30ac\u30fc\u30ca",
    "id": [33,
  11,
  185],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Triad Primus",
    "id": [2,
  45,
  150],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "LOVE LAIKA with Rosenburg Engel",
    "id": [125,
  12,
  47],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b5\u30f3\u30bb\u30c3\u30c8\u30ce\u30b9\u30bf\u30eb\u30b8\u30fc",
    "id": [3,
  186,
  160],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30bb\u30af\u30b7\u30fc\u30ae\u30eb\u30c6\u30a3",
    "id": [32,
  43,
  153],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30bb\u30af\u30b7\u30fc\u30d1\u30f3\u30b5\u30fc\u30ba",
    "id": [161,
  94,
  178],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30c1\u30a2\u30d5\u30eb\u30dc\u30f3\u30d0\u30fc\u30ba",
    "id": [138,
  139,
  197],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u51f8\u30ec\u30fc\u30b7\u30e7\u30f3",
    "id": [183,
  94,
  8],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d2\u30fc\u30c8\u30a2\u30c3\u30d7\u2606\u30c1\u30a2\u30fc\u30ba",
    "id": [197,
  78,
  163],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d6\u30a8\u30ca\u30fb\u30b9\u30a8\u30eb\u30c6",
    "id": [112,
  186,
  50],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "B.B.\u30ed\u30ef\u30a4\u30e4\u30eb",
    "id": [139,
  122,
  176],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Positive Passion",
    "id": [3,
  138,
  108],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u79cb\u8272\u6e29\u6cc9",
    "id": [29,
  185,
  65,
  101],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30bb\u30ec\u30af\u30c6\u30c3\u30c9",
    "id": [134,
  35,
  12,
  172],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30bb\u30f3\u30b4\u30af\u2606\u83ef\u2606\u30e9\u30f3\u30d6",
    "id": [127,
  198,
  132,
  92],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30c7\u30d3\u30ea\u30c3\u30b7\u30e5\u30b4\u30b7\u30c3\u30af",
    "id": [187,
  175,
  84,
  31],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30cf\u30a4\u30ab\u30e9\u30b5\u30af\u30e9",
    "id": [145,
  154,
  125,
  94],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d1\u30b9\u30c6\u30eb\u30fb\u30ab\u30af\u30c6\u30eb",
    "id": [61,
  87,
  102,
  162],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30cf\u30c3\u30d4\u30fc\u30d0\u30ec\u30f3\u30bf\u30a4\u30f3",
    "id": [88,
  134,
  74,
  117],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30cf\u30ed\u30a6\u30a3\u30f3\u30ca\u30a4\u30c8",
    "id": [127,
  91,
  182,
  26],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d6\u30e9\u30a4\u30c0\u30eb\u30bb\u30ec\u30af\u30b7\u30e7\u30f3",
    "id": [95,
  75,
  190,
  178],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d5\u30ea\u30eb\u30c9\u30b9\u30af\u30a8\u30a2",
    "id": [58,
  14,
  51,
  181],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30de\u30b8\u30ab\u30eb\u30c6\u30c3\u30c8",
    "id": [192,
  141,
  120,
  65],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30e1\u30eb\u30d8\u30f3\u30b4\u30b7\u30c3\u30af",
    "id": [83,
  36,
  182,
  97],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30e1\u30eb\u30d8\u30f3\u30a2\u30cb\u30de\u30eb\u30ba",
    "id": [42,
  4,
  39,
  49],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u3082\u308a\u304f\u307c\u3071\u30fc\u308a\u30fc",
    "id": [82,
  182,
  133,
  152],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ec\u30b8\u30a7\u30f3\u30c9\u30fb\u30d1\u30fc\u30c6\u30a3\u30fc",
    "id": [47,
  88,
  110,
  173],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ed\u30de\u30f3\u30c6\u30a3\u30c3\u30af\u30c4\u30a2\u30fc\u30ba",
    "id": [21,
  102,
  119,
  29],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\uff0a(Asterisk) with \u306a\u3064\u306a\u306a",
    "id": [154,
  109,
  53,
  13],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "FOUR PIECE",
    "id": [109,
  195,
  79,
  98],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Four Wind Colors",
    "id": [42,
  51,
  135,
  144],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "UK\u30b9\u30bf\u30a4\u30eb",
    "id": [98,
  62,
  101,
  178],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u9752\u68ee\u56db\u59c9\u59b9",
    "id": [11,
  58,
  175,
  168],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b3\u30ba\u30df\u30c3\u30af\u30fb\u30b7\u30f3\u30d5\u30a9\u30cb\u30fc",
    "id": [180,
  28,
  59,
  16],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Black\/White-Roses",
    "id": [113,
  10,
  83,
  100],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "GIRLS BE NEXT STEP",
    "id": [99,
  95,
  156,
  39],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d4\u30f3\u30af\u30c9\u30c3\u30c8\u30d0\u30eb\u30fc\u30f3",
    "id": [171,
  179,
  40,
  188],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ec\u30c7\u30a3\u30fb\u30d3\u30fc\u30b9\u30c8\u30fb\u30b7\u30e5\u30d7\u30ec\u30e0",
    "id": [52,
  136,
  4,
  105],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ab\u30ca\u30ea\u30a2\u30b5\u30de\u30fc",
    "id": [35,
  139,
  5,
  196],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30e9\u30a4\u30c8\u30b0\u30ea\u30fc\u30f3\u30bb\u30fc\u30d5",
    "id": [53,
  87,
  78,
  163],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u708e\u9663",
    "id": [174,
  143,
  157,
  189,
  53],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u685c\u821e\u968a",
    "id": [63,
  141,
  161,
  176,
  190],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u304b\u3089\u3071\u308c",
    "id": [31,
  188,
  198,
  184,
  116],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u6625\u971e",
    "id": [114,
  132,
  198,
  66,
  194],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30cf\u30ed\u30a6\u30a3\u30f3\u30d1\u30fc\u30c6\u30a3\u30fc",
    "id": [82,
  157,
  28,
  26,
  122],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d5\u30ec\u30c3\u30b7\u30e5\u30a2\u30b9\u30ea\u30fc\u30c6\u30b9",
    "id": [24,
  55,
  75,
  87,
  49],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30dd\u30cb\u30fc\u30c6\u30fc\u30eb\u4e59\u5973\u540c\u76df",
    "id": [5,
  88,
  153,
  167,
  197],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30de\u30fc\u30e1\u30a4\u30c9\u30d1\u30e9\u30c0\u30a4\u30b9",
    "id": [192,
  19,
  165,
  100,
  32],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30e1\u30a4\u30c9\u30b3\u30ec\u30af\u30b7\u30e7\u30f3",
    "id": [59,
  113,
  96,
  119,
  155],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30e6\u30e1\u30df\u30eb\u30ac\u30fc\u30eb\u30ba",
    "id": [83,
  84,
  178,
  191,
  196],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u5bb5\u4e59\u5973",
    "id": [103,
  86,
  13,
  170,
  43],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Happy Princess",
    "id": [93,
  46,
  138,
  73,
  82],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "LiPPS",
    "id": [134,
  89,
  172,
  22,
  93],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "LittlePOPS",
    "id": [145,
  94,
  126,
  133,
  96],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "NEX-US",
    "id": [12,
  45,
  117,
  154,
  152],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Sweetches",
    "id": [171,
  88,
  115,
  32,
  182],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30a2\u30a4\u30f3\u30d5\u30a7\u30ea\u30a2",
    "id": [125,
  81,
  110,
  108,
  6],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b5\u30de\u30d7\u30ea",
    "id": [46,
  138,
  153,
  26,
  122],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b9\u30a4\u30fc\u30c4\u30d5\u30a1\u30a4\u30d6",
    "id": [88,
  155,
  121,
  171,
  115],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Love Yell",
    "id": [19,
  139,
  168,
  183,
  42],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Masque:Rade",
    "id": [82,
  150,
  73,
  109,
  40],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30a4\u30a8\u30ed\u30fc\u30ea\u30ea\u30fc",
    "id": [162,
  117,
  88,
  168,
  24],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b5\u30af\u30e4\u30d2\u30e1",
    "id": [171,
  40,
  64,
  82,
  66],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "C5",
    "id": [13,
  1,
  73,
  145,
  154],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Heartful Bloom",
    "id": [13,
  19,
  40,
  114,
  133],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "la Roseraie",
    "id": [172,
  22,
  83,
  117,
  19],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u84bc\u30ce\u697d\u56e3",
    "id": [2,
  103,
  47,
  109,
  125],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30d6\u30eb\u30fc\u30ca\u30dd\u30ec\u30aa\u30f3",
    "id": [84,
  15,
  46,
  44,
  159],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ec\u30c3\u30c9\u30d0\u30e9\u30fc\u30c9",
    "id": [113,
  55,
  4,
  105,
  61],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "CAERULA",
    "id": [81,
  134,
  110,
  89,
  126],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Caskets",
    "id": [12,
  46,
  96,
  45,
  150],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b5\u30f3\u30d5\u30e9\u30ef\u30fc",
    "id": [139,
  23,
  43,
  35,
  6],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30bc\u30c3\u30b1\u30f3\u30ba",
    "id": [115,
  138,
  108,
  152,
  153],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30c8\u30ed\u30d4\u30ab\u30eb\u2606\u30b9\u30bf\u30fc\u30ba",
    "id": [94,
  183,
  93,
  3,
  8],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30b7\u30f3\u30c7\u30ec\u30e9\u30ac\u30fc\u30eb\u30ba",
    "id": [115,
  47,
  2,
  89,
  1,
  103],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30bb\u30af\u30b7\u30fc\u30dc\u30f3\u30c7\u30fc\u30b8",
    "id": [159,
  31,
  162,
  91,
  140,
  123],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30e0\u30fc\u30e9\u30f3\u30eb\u30fc\u30b8\u30e5",
    "id": [187,
  86,
  136,
  78,
  167,
  105,
  162,
  5,
  55],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ed\u30ef\u30a4\u30e4\u30eb\u30b9\u30bf\u30a4\u30eb",
    "id": [4,
  140,
  128,
  101,
  63,
  173,
  189],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ed\u30ef\u30a4\u30e4\u30eb\u30b9\u30bf\u30a4\u30ebNP",
    "id": [88,
  190,
  77,
  38,
  193,
  122,
  61,
  116,
  55,
  144,
  162],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ed\u30ef\u30a4\u30e4\u30eb\u30b9\u30bf\u30a4\u30ebND",
    "id": [59,
  130,
  60,
  127,
  159,
  185,
  91,
  188,
  197,
  148,
  141,
  30],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ed\u30ef\u30a4\u30e4\u30ebNC",
    "id": [32,
  44,
  186,
  179],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "\u30ef\u30f3\u30c0\u30fc\u30fb\u30d5\u30eb",
    "id": [26,
  177,
  49,
  85,
  79,
  10,
  128],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "CINDERELLA GIRLS",
    "id": [73,
  82,
  64,
  46,
  103,
  96,
  115,
  93,
  138],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "CINDERELLA PROJECT",
    "id": [1,
  2,
  3,
  8,
  12,
  40,
  47,
  94,
  109,
  125,
  145,
  154,
  171,
  183],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "L.M.B.G",
    "id": [84,
  192,
  141,
  196,
  63,
  110,
  120,
  57,
  85,
  65,
  188,
  121,
  37,
  161,
  23,
  8,
  83,
  178],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  },
  {
    "name": "Project:Krone",
    "id": [134,
  89,
  172,
  81,
  35,
  110,
  12,
  2,
  45,
  150],
    "fix": {
      "hp": null,
      "atk": 0.1,
      "pdef": 0.1,
      "mdef": 0.1,
      "hit": null,
      "dodge": null,
      "move": null,
      "range": null
    }
  }
];
