// Generated by CoffeeScript 2.2.3
var EnemyBase;

EnemyBase = class EnemyBase extends ObjectBase {
  constructor(params) {
    super(ObjectBase.OBJECT_TYPE.ENEMY);
    // 現在のレベル
    this.level = params.level;
    // 現在のHP
    this.hp = params.hp;
    // 出撃中であるか
    this.inField = params.inField;
    // 行動済みであるか
    this.moved = params.moved;
  }

  serialize() {
    return {
      type: this.getObjectType(),
      id: this.getId(),
      level: this.level,
      moved: this.moved,
      inField: this.inField,
      hp: this.hp
    };
  }

  getId() {
    return this.constructor.characterId;
  }

  getName() {
    return this.constructor.characterName;
  }

  isInField() {
    return this.inField;
  }

  setInField(isInField) {
    this.inField = !!isInField;
    return CharacterPalletManager.redraw(this);
  }

  isMoved() {
    return this.moved;
  }

  setMoved(bool) {
    return this.moved = !!bool;
  }

  static getInstance(id, params) {
    var classes;
    classes = EnemyDefine.getClasses();
    return new classes[id](params);
  }

};
